config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
               sessions: "auth/sessions",
               registrations: "auth/registrations",
             }

  # TODO: Remove html declaration for api-only controllers

  resources :packages do
    resources :categories
    resources :sources do
      collection do
        post :merge
      end
    end
    collection do
      get :search
    end
  end

  resource :endpoint, only: %i[show update] do
    resources :settings do
      collection do
        post :sync
      end
    end
    collection do
      post :clone
    end
  end

  resources :endpoints, only: %i[index create destroy] do
    resources :settings, only: %i[create]
  end

  authenticated :user do
    root to: "packages#index", as: :authenticated_root
  end
  root to: "packages#index" # TODO: products#landing?

  # namespace :api, defaults: { format: :json }, constraints: { subdomain: 'api' }, path: '/' do
  #  list of resources
  # end

  # This routes is only for non-API GET requests and must be in the end of route list

  resource :user, only: %i[show edit update]
  get ":user_id/:package_id", to: "packages#show"
  get ":id", to: "users#show"
  # match '*path', to: 'packages#show', via: [:get, :post]
end

app/models/endpoint.rb
class Endpoint < ApplicationRecord
  include IdentityCache
  include Blockable
  include Notifiable
  include TokenResetable

  # attribute :locale, :string, default: "en"

  belongs_to :user, optional: true
  has_many :settings, dependent: :destroy
  has_many :packages, through: :settings
  # TODO: Noticed has_many :notifications, as: :recipient, dependent: :destroy

  validates :name, length: { maximum: MAX_NAME_LENGTH }
  validates :locale, length: { maximum: 10 }

  def installed?(package)
    settings.exists?(package: package)
  end
end

app/controllers/endpoints_controller.rb
class EndpointsController < ApplicationController
  before_action :authenticate_user!, only: %i[index destroy]
  before_action :forbid_for_endpoint!, only: %i[index destroy]
  before_action :authenticate_endpoint!, only: %i[show update clone]
  before_action :set_endpoint, only: %i[update destroy clone]
  authorize_resource except: %i[show clone]

  # GET /endpoints
  # GET /endpoints.json
  def index
    @pagy, @endpoints =
      pagy_countless(current_user.endpoints, items: params[:items])
  end

  # GET /endpoints/1
  # GET /endpoints/1.json
  def show
    @endpoint = current_endpoint
    authorize! :show, @endpoint
    # TODO: @endpoint.touch
  end

  # POST /endpoints.json
  def create
    respond_to do |format|
      format.html { head :method_not_allowed }
      format.json do
        @endpoint = Endpoint.create!({
                                       name: endpoint_params[:name],
                                       user: current_user,
                                       remote_ip: request.remote_ip,
                                       locale: I18n.default_locale
                                     })
        sign_in_endpoint @endpoint
        render :show, status: :created, location: @endpoint
      end
    end
  end

  # PATCH/PUT /endpoint
  # PATCH/PUT /endpoint.json
  def update
    respond_to do |format|
      if @endpoint.update(endpoint_params)
        format.html do
          redirect_to @endpoint, notice: "Endpoint was successfully updated."
        end
        format.json { render :show, status: :ok, location: @endpoint }
      else
        format.html { render :edit }
        format.json do
          render_json_error @endpoint, status: :bad_request
        end
      end
    end
  end

  # DELETE /endpoints/1
  # DELETE /endpoints/1.json
  def destroy
    respond_to do |format|
      if @endpoint.destroy
        format.html do
          redirect_to endpoints_url,
                      notice: "Endpoint was successfully destroyed."
        end
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json do
          render_json_error @endpoint, status: :bad_request
        end
      end
    end
  end

  # POST /endpoint/clone
  # POST /endpoint/clone.json
  def clone
    from_endpoint = if params[:from_endpoint_id]
        Endpoint.find(params[:from_endpoint_id])
      else
        Endpoint.where.not(id: @endpoint.id).order(updated_at: :desc).first
      end
    authorize! :show, from_endpoint
    authorize! :update, @endpoint
    CloneEndpointService.call(from_endpoint, @endpoint)
    respond_to do |format|
      format.html do
        redirect_to @endpoint, notice: "Endpoint was successfully cloned."
      end
      format.json { render :show, status: :created, location: @endpoint }
    end
  end

  private

  def set_endpoint
    @endpoint = Endpoint.find(params[:endpoint_id] || params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def endpoint_params
    params.require(:endpoint).permit(:id, :name, :package)
  end
end

app/views/endpoints/_form.html.erb
<%= form_with(model: endpoint, local: true) do |form| %>
  <% if endpoint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(endpoint.errors.count, "error") %> prohibited this endpoint from being saved:</h2>

      <ul>
        <% endpoint.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/endpoints/edit.html.erb
<h1>Editing Endpoint</h1>

<%= render 'form', endpoint: @endpoint %>

<%= link_to 'Show', @endpoint %> |
<%= link_to 'Back', endpoints_path %>

app/views/endpoints/index.html.erb
<h1>Endpoints</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @endpoints.each do |endpoint| %>
      <tr>
        <td><%= link_to 'Show', endpoint %></td>
        <td><%= link_to 'Destroy', endpoint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/endpoints/new.html.erb
<h1>New Endpoint</h1>

<%= render 'form', endpoint: @endpoint %>

<%= link_to 'Back', endpoints_path %>

app/views/endpoints/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Back', endpoints_path %>