config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
               sessions: "auth/sessions",
               registrations: "auth/registrations",
             }

  # TODO: Remove html declaration for api-only controllers

  resources :packages do
    resources :categories
    resources :sources do
      collection do
        post :merge
      end
    end
    collection do
      get :search
    end
  end

  resource :endpoint, only: %i[show update] do
    resources :settings do
      collection do
        post :sync
      end
    end
    collection do
      post :clone
    end
  end

  resources :endpoints, only: %i[index create destroy] do
    resources :settings, only: %i[create]
  end

  authenticated :user do
    root to: "packages#index", as: :authenticated_root
  end
  root to: "packages#index" # TODO: products#landing?

  # namespace :api, defaults: { format: :json }, constraints: { subdomain: 'api' }, path: '/' do
  #  list of resources
  # end

  # This routes is only for non-API GET requests and must be in the end of route list

  resource :user, only: %i[show edit update]
  get ":user_id/:package_id", to: "packages#show"
  get ":id", to: "users#show"
  # match '*path', to: 'packages#show', via: [:get, :post]
end

app/views/home/index.html.erb
<% content_for :title, "Packages" %>

<h1>Packages</h1>

<table>
  <thead>
    <tr>
      <th colspan="4">Own packages</th>
    </tr>
  </thead>

  <tbody>
    <% @packages.select { |package| package.user == current_user }.map do |package| %>
      <tr>
        <td><%= package.name %></td>
        <td><%= link_to 'Show', package %></td>
        <td><%= link_to 'Edit', edit_package_path(package) %></td>
        <td><%= link_to 'Destroy', package, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Package', new_package_path %>

<br>